CREATE TABLE STUDENT1
(STUDENT_ID INTEGER NOT NULL,
SURNAME CHAR (25) NOT NULL,
NAME CHAR (10) NOT NULL,
STIPEND INTEGER,
KURS INTEGER,
CITY CHAR (15),
BIRTHDAY DATE,
UNIV_ID INTEGER)

/*
Сработает
*/
INSERT INTO STUDENT1 (STUDENT_ID,SURNAME, NAME)
VALUES (11,111,1111)
/*Не сработает
*/
INSERT INTO STUDENT1 (STUDENT_ID,SURNAME)
VALUES (11,111)