CREATE TABLE NEW_EXAM_MARKS
(STUDENT_ID CHAR (60)  NOT NULL,
SUBJ_ID	CHAR (60) NOT NULL,
MARK	INTEGER,
DATA	DATE,
UNIQUE (SUBJ_ID, STUDENT_ID)
)


INSERT INTO NEW_EXAM_MARKS
VALUES ('Федор','Рус Яз',5,'20-10-2007')

INSERT INTO NEW_EXAM_MARKS
VALUES ('Федор','Матем',5,'20-10-2007')